### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Quantum-Codes** [Sid72020123/pyhtmlchart#1]
why this has MIT license when this is for python? (Not scratch)

**Comment by Sid72020123** [comment]
Because I like Scratch so I use the MIT license.

**Comment by Sid72020123** [comment]
It is not compulsory to use the MIT license with Scratch only. You can use it for other things also.

**Comment by Quantum-Codes** [comment]
Hi, I dont get notifications :( can u help

**Comment by Sid72020123** [comment]
I don't know what's the problem. I receive notifications on my registered
email.

**Comment by Quantum-Codes** [comment]
Oh yeah... sorry, I figured it out! Actually when I get notifications, they are only sent to email. Now I changed setting to notify in the notifications tab on github
